services:

  nginx:
    build:
      context: requirements/nginx/
    ports:
      - "8080:80"
    
  mariadb:
    build:
      context: requirements/mariadb/
    
  wordpress:
    build:
      context: requirements/wordpress/
