services:

  nginx:
    build:
      context: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./wordpress_html:/var/www/html
    depends_on:
      - wordpress

  wordpress:
    build:
      context: requirements/wordpress/
    container_name: wordpress
    volumes:
      - ./wordpress_html:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env

  mariadb:
    build:
      context: requirements/mariadb/
    container_name: mariadb
    env_file:
      - .env
